### PR TITLE
Fix: Sluggify the database name

### LINKED ISSUE #88: FORGE_DB_NAME breaks if passed a branch name with a hypen
# Description

Databases specified with the FORGE_DB_NAME variable that include hyphens break the Create Database pipeline.

# Example

Setting this environment variable in the Github Action: 

FORGE_SITE_BRANCH: ${{ github.head_ref }}

 on a branch called `ABC-123` would result in it trying to create a database named `ABC-123` which is invalid: 
 
 ```
  INFO    Start finding the server.
  INFO    Finding the associated site.
  INFO    ---> Site not found.
  INFO    Creating a new site.
  INFO    ---> Use the specified Nginx template.
  INFO    Creating database.
  FAIL    ---> The name must only contain letters, numbers, and underscores.

   Laravel\Forge\Exceptions\ValidationException 

  The given data failed to pass validation.

  at /composer/vendor/laravel/forge-sdk/src/MakesHttpRequests.php:106
    102▕      */
    103▕     protected function handleRequestError(ResponseInterface $response)
    104▕     {
    105▕         if ($response->getStatusCode() == 422) {
  ➜ 106▕             throw new ValidationException(json_decode((string) $response->getBody(), true));
    107▕         }
    108▕ 
    109▕         if ($response->getStatusCode() == 404) {
    110▕             throw new NotFoundException();


Error: Process completed with exit code 1.

```

# Fix

Replace hyphens with underscores when setting the database name in the Forge Settings initialisation.

### PR DESCRIPTION
**Pull request by shawnhooper**
Fixes #88

### CODE REVIEW

File: app/Services/Forge/Pipeline/CreateDatabase.php [hunk 1]
```diff
@@ -28,8 +29,13 @@ public function __invoke(ForgeService $service, Closure $next)
...
         }
 
+        if ( $service->setting->dbName ) {
+            $dbName = FormattedBranchName::run($service->setting->dbName);
+        } else {
+            $dbName = $service->getStandardizedBranchName();
+        }
+
         $dbPassword = Str::random(16);
-        $dbName = $service->setting->dbName ?? $service->getStandardizedBranchName();
```
Comment (mehrancodes) [inline app/Services/Forge/Pipeline/CreateDatabase.php:32]: It turns out I created an action called "GenerateStandardizedBranchName" that generates the database name from the branch name, removing the first digit of string the db name as well. It would be great if we can get db name from the **getFormattedBranchName** through the **GetStandardizedBranchName** (perhaps with a name change in the **GetStandardizedBranchName** to **getFormattedDatabaseName**) and it will be safe :) Thanks again for your time!

Comment (shawnhooper) [reply app/Services/Forge/Pipeline/CreateDatabase.php:32]: I've updated my PR to include use the GenerateStandardizedBranchName action instead of Laravel's Str helper. I've created a new `getFormattedDatabaseName` method in the ForgeService to generate the new DB name, with the formatted branch name as the fallback.

**Comment by mehrancodes** [comment]
I also added the new function to the RemoveDatabaseUser class. Did a couple of tests using other characters (FORGE_DB_NAME=abc+11@database) to ensure we are safe but we got forge validation error: 

```bash
  FAIL    ---> The name must only contain letters, numbers, and underscores.
  FAIL    ---> The user field must only contain letters, numbers, dashes, and underscores.
```

I have added a regex rule to the **db_name** to ensure we throw err before the site gets created with crash. This allows us to keep the current behavior when db_name not provided.

**Comment by mehrancodes** [comment]
I tried to load the validation messages from the **resources/lang/en/validation** but Harbor loads messages from default vendor path. We may need some time to fix this, but for now I have [specified db_name.regex err message](https://github.com/mehrancodes/laravel-harbor/pull/89/files#diff-74e7252181b42dbb755579ad900dc3468bec32a2fcd2e8073fa39ebccf027d05R230-R233) while doing validation.

**Comment by mehrancodes** [comment]
It's time to merge if we're all good. I'd love to hear what you think!

**Comment by mehrancodes** [comment]
That's great to hear! I appreciate it!
